import doc1 from '../Images/Doctors/doc1.jpg';
import doc2 from '../Images/Doctors/doc2.jpg';
import doc3 from '../Images/Doctors/doc3.jpg';
import doc4 from '../Images/Doctors/doc4.jpg';
import doc5 from '../Images/Doctors/doc5.jpg';
import doc6 from '../Images/Doctors/doc6.jpg';
import doc7 from '../Images/Doctors/doc7.jpg';

export const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

export const DoctorsList = [
  {
    key: '1',
    doctor_name: 'Dr.Johnny',
    type: 'Dermatologist',
    experience: '8',
    contact_number: '9876543210',
    course: 'MBBS',
    photo: doc1,
    available: 'Saturday',
  },
  {
    key: '2',
    doctor_name: 'Dr.ArunVijay',
    type: 'Physician',
    experience: '6',
    contact_number: '9876543200',
    course: 'MS',
    photo: doc2,
    available: 'Sunday',
  },
  {
    key: '3',
    doctor_name: 'Dr.Kumar',
    type: 'Orthopedician',
    experience: '4',
    contact_number: '9876543211',
    course: 'MBBS',
    photo: doc3,
    available: 'Monday',
  },
  {
    key: '4',
    doctor_name: 'Dr.Rajesh',
    type: 'Physician',
    experience: '4',
    contact_number: '9876543222',
    course: 'MS',
    photo: doc4,
    available: 'Tuesday',
  },
  {
    key: '5',
    doctor_name: 'Dr.Sajith',
    type: 'Orthopedician',
    experience: '9',
    contact_number: '9876543233',
    course: 'MBBS',
    photo: doc5,
    available: 'Wednesday',
  },

  {
    key: '6',
    doctor_name: 'Dr.KaviArasan',
    type: 'Physician',
    experience: '7',
    contact_number: '9876543244',
    course: 'MD',
    photo: doc6,
    available: 'Friday',
  },
  {
    key: '7',
    doctor_name: 'Dr.Adlin',
    type: 'Dermatologist',
    experience: '9',
    contact_number: '9876543255',
    course: 'MD',
    photo: doc7,
    available: 'Saturday',
  },
  {
    key: '8',
    doctor_name: 'Dr.Dixson',
    type: 'ophthalmologist',
    experience: '5',
    contact_number: '9876333255',
    course: 'MD',
    photo: doc3,
    available: 'Monday',
  },
  {
    key: '9',
    doctor_name: 'Dr.Aswin',
    type: 'ophthalmologist',
    experience: '9',
    contact_number: '9116543255',
    course: 'MD',
    photo: doc1,
    available: 'Tuesday',
  },
  {
    key: '10',
    doctor_name: 'Dr.Abinash',
    type: 'Dietitians',
    experience: '2',
    contact_number: '9876543044',
    course: 'Nutrition&Dietetics',
    photo: doc7,
    available: 'Thursday',
  },
];

export const DoctorsList2 = [
  {
    key: '1',
    doctor_name: 'Dr.Johnny',
    type: 'Dermatologist',
    experience: '8',
    contact_number: '9876543210',
    course: 'MBBS',
    photo: doc1,
    category: [
      {key: '1', symptom: 'Pimples'},
      {key: '2', symptom: 'Hairfall'},
      {key: '3', symptom: 'Itching'},
      {key: '4', symptom: 'Dark Circles'},
      {key: '5', symptom: 'Hair Care'},
      {key: '6', symptom: 'Skin Care'},
      {key: '7', symptom: 'Acne & Scar'},
    ],
  },
  {
    key: '2',
    doctor_name: 'Dr.ArunVijay',
    type: 'Physician',
    experience: '6',
    contact_number: '9876543200',
    course: 'MS',
    photo: doc2,
    category: [
      {key: '1', symptom: 'Fever'},
      {key: '2', symptom: 'Cough'},
      {key: '3', symptom: 'Headache'},
      {key: '4', symptom: 'Low BP'},
      {key: '5', symptom: 'High BP'},
      {key: '6', symptom: 'Migrane'},
      {key: '7', symptom: 'Throat Pain'},
    ],
  },
  {
    key: '3',
    doctor_name: 'Dr.Kumar',
    type: 'Orthopedician',
    experience: '4',
    contact_number: '9876543211',
    course: 'MBBS',
    photo: doc3,
    category: [
      {key: '1', symptom: 'Back Pain'},
      {key: '2', symptom: 'Heel Pain'},
      {key: '3', symptom: 'Shoulder Pain'},
      {key: '4', symptom: 'Neck pain'},
    ],
  },
  {
    key: '4',
    doctor_name: 'Dr.Rajesh',
    type: 'Physician',
    experience: '4',
    contact_number: '9876543222',
    course: 'MS',
    photo: doc4,
    category: [
      {key: '1', symptom: 'Fever'},
      {key: '2', symptom: 'Cough'},
      {key: '3', symptom: 'Headache'},
      {key: '4', symptom: 'Low BP'},
      {key: '5', symptom: 'High BP'},
      {key: '6', symptom: 'Migrane'},
      {key: '7', symptom: 'Throat Pain'},
    ],
  },
  {
    key: '5',
    doctor_name: 'Dr.Sajith',
    type: 'Orthopedician',
    experience: '9',
    contact_number: '9876543233',
    course: 'MBBS',
    photo: doc5,
    category: [
      {key: '1', symptom: 'Back Pain'},
      {key: '2', symptom: 'Heel Pain'},
      {key: '3', symptom: 'Shoulder Pain'},
      {key: '4', symptom: 'Neck pain'},
    ],
  },
  {
    key: '10',
    doctor_name: 'Dr.Abinash',
    type: 'Dietitians',
    experience: '2',
    contact_number: '9876543044',
    course: 'Nutrition&Dietetics',
    photo: doc7,
    category: [
      {key: '1', symptom: 'Diet for Weight Gaining'},
      {key: '2', symptom: 'Diet for Weight loss'},
      {key: '3', symptom: 'Diet for Diabetes'},
    ],
  },
  {
    key: '6',
    doctor_name: 'Dr.KaviArasan',
    type: 'Physician',
    experience: '7',
    contact_number: '9876543244',
    course: 'MD',
    photo: doc6,
    category: [
      {key: '1', symptom: 'Fever'},
      {key: '2', symptom: 'Cough'},
      {key: '3', symptom: 'Headache'},
      {key: '4', symptom: 'Low BP'},
      {key: '5', symptom: 'High BP'},
      {key: '6', symptom: 'Migrane'},
      {key: '7', symptom: 'Throat Pain'},
    ],
  },
  {
    key: '7',
    doctor_name: 'Dr.Adlin',
    type: 'Dermatologist',
    experience: '9',
    contact_number: '9876543255',
    course: 'MD',
    photo: doc7,
    category: [
      {key: '1', symptom: 'Pimples'},
      {key: '2', symptom: 'Hairfall'},
      {key: '3', symptom: 'Itching'},
      {key: '4', symptom: 'Dark Circles'},
      {key: '5', symptom: 'Hair Care'},
      {key: '6', symptom: 'Skin Care'},
      {key: '7', symptom: 'Acne & Scar'},
    ],
  },
  {
    key: '8',
    doctor_name: 'Dr.Dixson',
    type: 'ophthalmologist',
    experience: '5',
    contact_number: '9876333255',
    course: 'MD',
    photo: doc3,
    category: [
      {key: '1', symptom: 'Readness of Eye'},
      {key: '2', symptom: 'Itching of Eyes'},
    ],
  },
  {
    key: '9',
    doctor_name: 'Dr.Aswin',
    type: 'ophthalmologist',
    experience: '9',
    contact_number: '9116543255',
    course: 'MD',
    photo: doc1,
    category: [
      {key: '1', symptom: 'Readness of Eye'},
      {key: '2', symptom: 'Itching of Eyes'},
    ],
  },
];
